name: spell

on:
  pull_request:

  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  spell:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2.1
