name: spell

on:
  pull_request:

  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  spell:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2.1
