name: spell

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  spell:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461 # v2.0
